import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config";
import Web3ModalProvider from "@/context";
import Footer from "./components/Footer";
import { ToastContainer } from "react-toastify";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <Web3ModalProvider initialState={initialState}>
          <main className="flex flex-col px-12 py-2">
            <Navbar />

            <div className="flex mt-8 justify-center items-center">
              {children}
            </div>
          </main>
          {/*         <Footer></Footer> */}
          <ToastContainer />
        </Web3ModalProvider>
      </body>
    </html>
  );
}
